# @package _global_

defaults:
  - _self_
  - experiments: default
  - data: teaser

log_dir: /home/zhexi/project/easyhoi/outputs
out_dir: /home/zhexi/project/easyhoi/outputs/log
hand_scale: 10

hydra:
  run:
